"""create db

Revision ID: a83db77da908
Revises: 
Create Date: 2025-10-13 23:29:13.838780

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a83db77da908'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('container_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('ports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('port_pairs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('origin_port_id', sa.Integer(), nullable=False),
    sa.Column('destination_port_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['destination_port_id'], ['ports.id'], name=op.f('fk_port_pairs_destination_port_id_ports')),
    sa.ForeignKeyConstraint(['origin_port_id'], ['ports.id'], name=op.f('fk_port_pairs_origin_port_id_ports')),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('origin_port_id', 'destination_port_id', name='uniq_pair')
    )
    op.create_table('quotes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_quotes_user_id_users')),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('port_pair_id', sa.Integer(), nullable=False),
    sa.Column('container_type_id', sa.Integer(), nullable=False),
    sa.Column('base_rate', sa.Float(), nullable=False),
    sa.Column('transit_days', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['container_type_id'], ['container_types.id'], name=op.f('fk_rates_container_type_id_container_types')),
    sa.ForeignKeyConstraint(['port_pair_id'], ['port_pairs.id'], name=op.f('fk_rates_port_pair_id_port_pairs')),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('quote_rates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quote_id', sa.Integer(), nullable=False),
    sa.Column('rate_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['quote_id'], ['quotes.id'], name=op.f('fk_quote_rates_quote_id_quotes')),
    sa.ForeignKeyConstraint(['rate_id'], ['rates.id'], name=op.f('fk_quote_rates_rate_id_rates')),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('quote_id', 'rate_id', name='uniq_quote_rate')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('quote_rates')
    op.drop_table('rates')
    op.drop_table('quotes')
    op.drop_table('port_pairs')
    op.drop_table('users')
    op.drop_table('ports')
    op.drop_table('container_types')
    # ### end Alembic commands ###
